In [54]:
import pandas as pd
data=pd.read_csv("train.csv")

In [55]:
new_data=data.dropna()

In [56]:
new_data.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis='columns',inplace=True)

In [57]:
main_data=new_data.drop('Survived',axis='columns')
target=new_data.Survived

In [58]:
main_data.Sex=main_data.Sex.map({'male':1,'female':2})
main_data.head()

    Pclass  Sex   Age     Fare
1        1    2  38.0  71.2833
3        1    2  35.0  53.1000
6        1    1  54.0  51.8625
10       3    2   4.0  16.7000
11       1    2  58.0  26.5500

In [59]:
main_data.Age[:10]

1     38.0
3     35.0
6     54.0
10     4.0
11    58.0
21    34.0
23    28.0
27    19.0
52    49.0
54    65.0
Name: Age, dtype: float64

In [60]:
main_data.Age=main_data.Age.fillna(main_data.Age.mean())
main_data.head()

    Pclass  Sex   Age     Fare
1        1    2  38.0  71.2833
3        1    2  35.0  53.1000
6        1    1  54.0  51.8625
10       3    2   4.0  16.7000
11       1    2  58.0  26.5500

In [61]:
from sklearn.model_selection import train_test_split

In [62]:
X_train, X_test, y_train, y_test = train_test_split(main_data,target, test_size=0.2)

In [63]:
len(X_train)

146

In [64]:
len(X_test)

37